// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ph3pErDSWtm-yVyQpvkWro0hI4goDCo',
    appId: '1:936219219713:web:426a0cf65bc0bc47e1ed00',
    messagingSenderId: '936219219713',
    projectId: 'testes-classe-flutter',
    authDomain: 'testes-classe-flutter.firebaseapp.com',
    storageBucket: 'testes-classe-flutter.firebasestorage.app',
    measurementId: 'G-WSZZSQNHW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaW85cW1pAeb0mcmGxKNPVTQDO7Ux8XLU',
    appId: '1:936219219713:android:e45c62970359ad70e1ed00',
    messagingSenderId: '936219219713',
    projectId: 'testes-classe-flutter',
    storageBucket: 'testes-classe-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqlgjm-6NSkuyZKcZrGwHbtBLWFBFqyQ',
    appId: '1:936219219713:ios:703ff30dcb6ab7ebe1ed00',
    messagingSenderId: '936219219713',
    projectId: 'testes-classe-flutter',
    storageBucket: 'testes-classe-flutter.firebasestorage.app',
    iosBundleId: 'com.kodersolutions.firebaseWithFlutter',
  );

}